import { useState } from "react";
import { ChevronDown, ChevronRight, Globe, DollarSign, Users, HelpCircle, Lock, Settings } from "lucide-react";
import Header from "../components/Header";
import { Link } from 'react-router-dom';

// FAQ organizzate per categorie
const faqCategories = [
  {
    id: "basics",
    name: "General Information",
    icon: <Globe className="h-5 w-5" />,
    faqs: [
      {
        question: "What is Fast Affiliation?",
        answer:
          "We are an Affiliate Marketing platform where you can select campaigns from our clients and promote them on your website or social media. You will earn a commission for each user who registers or completes an action through your affiliate link.",
      },
      {
        question: "How can I sign up?",
        answer: (
          <p>
            Signing up is free and only takes a few minutes. Click{" "}
            <Link to="/signup" className="text-green-600 font-medium hover:underline">
              here
            </Link>{" "}
            to sign up and follow the instructions.
          </p>
        ),
        isJSX: true
      },
      {
        question: "Do I need a website to join Fast Affiliation?",
        answer:
          "It is not mandatory, but you must indicate your traffic sources (website, social media, email, etc.). We recommend contacting one of our managers to ensure your marketing strategy aligns with our network's requirements.",
      },
      {
        question: "Can I use multiple traffic sources?",
        answer:
          "Yes, you can register multiple traffic sources in your affiliate account.",
      },
      {
        question: "Is it legal to promote iGaming programs?",
        answer:
          "Yes, it is legal in the countries where we offer our services, but it is important to comply with the applicable laws.",
      }
    ]
  },
  {
    id: "earnings",
    name: "Earnings & Commissions",
    icon: <DollarSign className="h-5 w-5" />,
    faqs: [
      {
        question: "How can I earn with Fast Affiliation?",
        answer: [
          "Select the campaigns you are most interested in, such as sports betting, casino, poker, or finance/FOREX.",
          "You will receive a personalized link to promote the campaigns.",
          "You will earn a commission every time a user registers or completes a specific action through your link.",
          "Earnings Example:",
          "Let's assume you choose a campaign that pays €45 per CPA (Cost per Action). If 50 users register through your link, you will earn €2,250 (50 x €45)."
        ],
      },
      {
        question: "How much can I earn with Fast Affiliation?",
        answer:
          "There are no limits! It depends on how many users you can bring to the campaigns. The more users convert through your links, the more you will earn.",
      },
      {
        question: "What types of commission offers are available?",
        answer: [
          "We generally offer CPA (Cost per Action), Revenue Share, and Hybrid offers.",
          "CPA: You earn a fixed commission when a user completes a specific action, such as registration or first deposit.",
          "Revenue Share: You earn a percentage of the losses generated by users who registered through your link.",
          "Hybrid: A combination of CPA and Revenue Share."
        ],
      },
      {
        question: "Can I earn by referring other affiliates?",
        answer:
          "Yes, many affiliate programs offer 5% of the commissions earned by the affiliates you refer.",
      },
      {
        question: "Can I earn from my own gaming activities?",
        answer:
          "No, earning from your own gaming activities is not allowed.",
      }
    ]
  },
  {
    id: "payments",
    name: "Payments & Withdrawals",
    icon: <DollarSign className="h-5 w-5" />,
    faqs: [
      {
        question: "How can I withdraw my commissions?",
        answer:
          "We offer various options to withdraw your earnings: Paypal or Crypto",
      },
      {
        question: "When are payments made?",
        answer:
          "Payments are generally processed twice a month, on the 1st and 15th of each month. Payments are also made every 7 days for top-tier publishers. Some platforms process payments on the 30th of the month.",
      },
      {
        question: "What is the minimum payout threshold?",
        answer:
          "The minimum payout threshold is €100, but some programs allow payments starting from €50.",
      }
    ]
  },
  {
    id: "account",
    name: "Account Management",
    icon: <Users className="h-5 w-5" />,
    faqs: [
      {
        question: "How is my account verified?",
        answer:
          "Our team will verify that your traffic sources meet our requirements, such as:\n\nValidity of the source\nQuality of content and design\nTraffic coming from selected countries\nWe reserve the right to reject applications.",
      },
      {
        question: "Can I have affiliate accounts with other platforms?",
        answer:
          "Yes, you can have affiliate accounts with other operators and still join Fast Affiliation.",
      },
      {
        question: "How can I reset my password?",
        answer:
          "Use the \"reset password\" link to reset your password.",
      }
    ]
  },
  {
    id: "marketing",
    name: "Marketing & Promotion",
    icon: <Settings className="h-5 w-5" />,
    faqs: [
      {
        question: "How can I get marketing materials?",
        answer:
          "Marketing materials for approved campaigns are available in the \"campaigns\" section of your account. Copy the HTML code and integrate it into your traffic source.",
      },
      {
        question: "How many links can I place on my traffic source?",
        answer:
          "You can insert as many links as you want, but the code cannot be modified.",
      },
      {
        question: "How are performance reports updated?",
        answer:
          "Reports are updated daily for most campaigns. Contact your manager to know when the last update was made.",
      },
      {
        question: "Important Notes:",
        answer:
          "Do not suggest players make the minimum deposit, as some bookmakers consider this fraudulent.\nAlways read the Terms and Conditions of the affiliate programs.",
      }
    ]
  },
  {
    id: "support",
    name: "Support & Contact",
    icon: <HelpCircle className="h-5 w-5" />,
    faqs: [
      {
        question: "How can I contact you for further questions?",
        answer: (
          <p>
            You can contact us from form {" "}
            <Link to="/contact" className="text-green-600 font-medium hover:underline">
              here
            </Link>{" "}
            or through the support area if you are already registered.
          </p>
        ),
        isJSX: true
      }
    ]
  }
];

export default function FAQ() {
  const [activeCategory, setActiveCategory] = useState("basics");
  const [openIndex, setOpenIndex] = useState(null);

  // Funzione per formattare correttamente le risposte (array o stringa)
  const formatAnswer = (answer) => {
    if (Array.isArray(answer)) {
      return (
        <ul className="list-disc pl-5 space-y-2 mt-3">
          {answer.map((item, index) => (
            <li key={index}>{item}</li>
          ))}
        </ul>
      );
    }
    return <p className="mt-3 text-lg text-gray-600">{answer}</p>;
  };

  return (
    <div className="App min-h-screen bg-white text-custom-black">
      <Header />
      <div className="max-w-6xl mx-auto py-10 px-4">
        <h1 className="text-4xl font-bold text-center mt-4">Welcome to the Fast Affiliation FAQ section.</h1>
        <p className="text-center text-lg text-gray-600 mt-2 mb-8">
          Here you will find answers to the most common questions about our affiliate program.
        </p>

        {/* Navigazione categorica */}
        <div className="flex flex-wrap justify-center gap-2 mb-8 sticky top-0 bg-white py-3 z-10 border-b">
          {faqCategories.map((category) => (
            <button
              key={category.id}
              onClick={() => setActiveCategory(category.id)}
              className={`flex items-center gap-2 px-4 py-2 rounded-full transition-all ${
                activeCategory === category.id 
                  ? "bg-green-600 text-white shadow-md" 
                  : "bg-gray-100 hover:bg-gray-200 text-gray-800"
              }`}
            >
              {category.icon}
              {category.name}
            </button>
          ))}
        </div>

        {/* Mostra solo le FAQ della categoria attiva */}
        <div className="mt-6 space-y-4">
          {faqCategories
            .find(cat => cat.id === activeCategory)
            ?.faqs.map((faq, index) => (
              <div
                key={index}
                className={`border shadow-md rounded-xl p-6 transition-all ${
                  openIndex === index ? "border-green-600" : "border-gray-300"
                }`}
              >
                <button
                  className="w-full flex justify-between items-center text-left text-xl font-semibold"
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                >
                  {faq.question}
                  {openIndex === index ? (
                    <ChevronDown className="text-green-600 flex-shrink-0" />
                  ) : (
                    <ChevronRight className="text-gray-600 flex-shrink-0" />
                  )}
                </button>
                {openIndex === index && formatAnswer(faq.answer)}
              </div>
            ))}
        </div>
      </div>
    </div>
  );
}